### ISSUE TITLE
Реализовать set метод у DataBaseManager

### ISSUE THREAD

**Issue by Ivan-Veselov** [Ivan-Veselov/sql-homework#12]
Нужно реализовать set метод (`setAthleteInfo`) у `DataBaseManager`.

Нужно разобраться с JPA, проаннотировать классы из файла `Entities.kt` и написать сам метод. Смотри класс `CreatePlanetHandler` у Барашева в примере для Java.

**Comment by shavkunov** [comment]
Почему это здесь висит?
