### ISSUE TITLE
Response для /sportsman/set

### ISSUE THREAD

**Issue by shavkunov** [Ivan-Veselov/sql-homework#19]
Хочется, чтобы на этот запрос сервер мне что-нибудь отвечал.
Если все прошло успешно, то вероятно меня устроит просто какой-нибудь ответ в виде:
```javascript
response {
    type: "OK",
    message: "Query is executed"
}
```
Если все прошло плохо, то:
```javascript
response {
    type: "ERROR",
    message: "Message related to error"
}
```
Я не уверен, но можно сделать вообще ко всем объектам. В смысле всегда возвращать мне нечто, где есть поле type и если там будет какая-то ошибка, то я бы мог отобразить ее пользователю.

**Comment by Ivan-Veselov** [comment]
Нормально, если изменения коснуться всех json форматов, которые сейчас уже есть? Я могу сдеалть json объект response, который будет содержать в себе type, а в случае удачного запроса атрибут result, который будет одним из тех объектов, которые сейчас задекларированы.

**Comment by shavkunov** [comment]
Норм конечно
